"use strict";
//** ---- Imports
Object.defineProperty(exports, "__esModule", { value: true });
var professional_1 = require("./professional");
var movie_1 = require("./movie");
//** ---- Declaracion de objetos
// Professional
var johnTravolta = new professional_1.Professional("John Travolta", 70, 90, 188, false, "American", 0, "Actor");
var umaThurman = new professional_1.Professional("Uma Thurman", 50, 64, 180, false, "American", 0, "Actress");
var samuelLJackson = new professional_1.Professional("Samuel L. Jackson", 75, 94, 189, false, "American", 1, "Actor");
var bruceWillis = new professional_1.Professional("Bruce Willis", 65, 93, 183, false, "American", 0, "Actor");
var quentinTarantino = new professional_1.Professional("Quentin Tarantino", 61, 90, 185, false, "American", 2, "Director");
var elijahWood = new professional_1.Professional("Elijah Wood", 43, 64, 168, false, "American", 0, "Actor");
var ianMcKellen = new professional_1.Professional("Ian McKellen", 85, 80, 180, false, "British", 0, "Actor");
var viggoMortensen = new professional_1.Professional("Viggo Mortensen", 65, 81, 180, false, "American", 0, "Actor");
var seanAstin = new professional_1.Professional("Sean Astin", 53, 85, 170, false, "American", 0, "Actor");
var peterJackson = new professional_1.Professional("Peter Jackson", 63, 120, 169, false, "New Zealander", 3, "Director");
var franWalsh = new professional_1.Professional("Fran Walsh", 63, 60, 165, false, "New Zealander", 3, "Screenwriter");
var maribelVerdu = new professional_1.Professional("Maribel Verdú", 50, 60, 165, false, "Spanish", 0, "Actress");
var ivanaBaquero = new professional_1.Professional("Ivana Baquero", 30, 55, 160, false, "Spanish", 0, "Actress");
var dougJones = new professional_1.Professional("Doug Jones", 64, 64, 192, false, "American", 0, "Actor");
var ariadnaGil = new professional_1.Professional("Ariadna Gil", 51, 56, 168, false, "Spanish", 0, "Actress");
var guillermoDelToro = new professional_1.Professional("Guillermo del Toro", 55, 100, 178, false, "Mexican", 0, "Director");
var javierCamara = new professional_1.Professional("Javier Cámara", 53, 70, 170, false, "Spanish", 0, "Actor");
var carlosAreces = new professional_1.Professional("Carlos Areces", 48, 75, 170, false, "Spanish", 0, "Actor");
var raulArevalo = new professional_1.Professional("Raúl Arévalo", 42, 70, 175, false, "Spanish", 0, "Actor");
var lolaDuenas = new professional_1.Professional("Lola Dueñas", 49, 65, 165, false, "Spanish", 0, "Actress");
var pedroAlmodovar = new professional_1.Professional("Pedro Almodóvar", 72, 75, 178, false, "Spanish", 0, "Director");
var robertDeNiro = new professional_1.Professional("Robert De Niro", 76, 75, 177, false, "American", 0, "Actor");
var alPacino = new professional_1.Professional("Al Pacino", 79, 75, 170, false, "American", 0, "Actor");
var joePesci = new professional_1.Professional("Joe Pesci", 76, 70, 163, false, "American", 0, "Actor");
var harveyKeitel = new professional_1.Professional("Harvey Keitel", 80, 75, 170, false, "American", 0, "Actor");
var martinScorsese = new professional_1.Professional("Martin Scorsese", 77, 70, 163, false, "American", 0, "Director");
var stevenZaillian = new professional_1.Professional("Steven Zaillian", 67, 80, 170, false, "American", 0, "Screenwriter");
var robertDowneyJr = new professional_1.Professional("Robert Downey Jr.", 55, 78, 174, false, "American", 0, "Actor");
var chrisEvans = new professional_1.Professional("Chris Evans", 38, 88, 183, false, "American", 0, "Actor");
var markRuffalo = new professional_1.Professional("Mark Ruffalo", 52, 80, 173, false, "American", 0, "Actor");
var chrisHemsworth = new professional_1.Professional("Chris Hemsworth", 36, 91, 190, false, "Australian", 0, "Actor");
var anthonyRusso = new professional_1.Professional("Anthony Russo", 50, 90, 183, false, "American", 0, "Director");
var christopherMarkus = new professional_1.Professional("Christopher Markus", 51, 85, 178, false, "American", 0, "Screenwriter");
// Movie
var movie1 = new movie_1.Movie("Pulp Fiction", 1994, "American", "Crime");
movie1.actors = [johnTravolta, umaThurman, samuelLJackson, bruceWillis];
movie1.director = quentinTarantino;
movie1.writer = quentinTarantino;
movie1.languaje = "English";
movie1.platform = "Cinema";
movie1.isMCU = false;
movie1.mainCharacterName = "Vincent Vega";
movie1.producer = "Lawrence Bender";
movie1.distributor = "Miramax Films";
var movie2 = new movie_1.Movie("The Lord of the Rings: The Return of the King", 2003, "New Zealand", "Fantasy");
movie2.actors = [elijahWood, ianMcKellen, viggoMortensen, seanAstin];
movie2.director = peterJackson;
movie2.writer = franWalsh;
movie2.languaje = "English";
movie2.platform = "Cinema";
movie2.isMCU = false;
movie2.mainCharacterName = "Frodo Baggins";
movie2.producer = "Barrie M. Osborne";
movie2.distributor = "New Line Cinema";
var movie3 = new movie_1.Movie("El laberinto del fauno", 2006, "Spanish", "Fantasy");
movie3.actors = [maribelVerdu, ivanaBaquero, dougJones, ariadnaGil];
movie3.director = guillermoDelToro;
movie3.writer = guillermoDelToro;
movie3.languaje = "Spanish";
movie3.platform = "Cinema";
movie3.isMCU = false;
movie3.mainCharacterName = "Ofelia";
movie3.producer = "Guillermo del Toro";
movie3.distributor = "Warner Bros";
var movie4 = new movie_1.Movie("Los amantes pasajeros", 2013, "Spanish", "Comedy");
movie4.actors = [javierCamara, carlosAreces, raulArevalo, lolaDuenas];
movie4.director = pedroAlmodovar;
movie4.writer = pedroAlmodovar;
movie4.languaje = "Spanish";
movie4.platform = "Cinema";
movie4.isMCU = false;
movie4.mainCharacterName = "Joserra";
movie4.producer = "Agustín Almodóvar";
movie4.distributor = "Sony Pictures Releasing";
var movie5 = new movie_1.Movie("The Irishman", 2019, "American", "Crime");
movie5.actors = [robertDeNiro, alPacino, joePesci, harveyKeitel];
movie5.director = martinScorsese;
movie5.writer = stevenZaillian;
movie5.languaje = "English";
movie5.platform = "Netflix";
movie5.isMCU = false;
movie5.mainCharacterName = "Frank Sheeran";
movie5.producer = "Robert De Niro";
movie5.distributor = "Netflix";
var movie6 = new movie_1.Movie("Avengers: Endgame", 2019, "American", "Superhero");
movie6.actors = [robertDowneyJr, chrisEvans, markRuffalo, chrisHemsworth];
movie6.director = anthonyRusso;
movie6.writer = christopherMarkus;
movie6.languaje = "English";
movie6.platform = "Cinema";
movie6.isMCU = true;
movie6.mainCharacterName = "Tony Stark / Iron Man";
movie6.producer = "Kevin Feige";
movie6.distributor = "Walt Disney Studios Motion Pictures";
//** ---- Main
movie1.printMovie();
movie2.printMovie();
movie3.printMovie();
movie4.printMovie();
movie5.printMovie();
movie6.printMovie();
